vich_uploader:
    db_driver: orm

    mappings:
        recipe_image:
           uri_prefix: /recipe/images
           upload_destination: '%kernel.project_dir%/public/recipe/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
