vich_uploader:
    db_driver: orm

    mappings:
        post_image:
           uri_prefix: /post/images
           upload_destination: '%kernel.project_dir%/public/post/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
